settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: RenmeriMaker
  path: server
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ./
    ignored_paths:
    - .git
    - .realize
    - vendor
