debug:
    mysql:
        protocol: tcp
        host: localhost
        user: root
        port: 3306
        database: your_database
    application:
        host: localhost:8080
release:
    mysql:
        protocol: tcp
        host: localhost
        user: root
        port: 3306
        database: your_database
    application:
        host: localhost:8080
